name: Build Vita3K for UWP

on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      # Step 1: Set up Visual Studio 2022 with C++ workload
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2

      # Step 2: Checkout the repository with submodules
      - name: Checkout Vita3K repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      # Step 3: Install a specific version of CMake (optional)
      - name: Install CMake
        run: |
          choco install cmake --version=3.22.2 --confirm
          cmake --version
          
      # Step 4: Generate the Visual Studio project with CMake
      - name: Generate project with CMake
        run: cmake --preset windows-vs2022

      # Step 5: Build the project
      - name: Build the project
        run: cmake --build build/windows-vs2022 --config Release

      # Step 6: Archive the build if needed
      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Vita3K-Build
          path: build/windows-vs2022/bin/Release
