name: Build Vita3K for UWP

on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      # Step 1: Set up Visual Studio 2022 with C++ workload
      - name: Setup Visual Studio 2022
        uses: microsoft/setup-msbuild@v2

      # Step 2: Checkout the repository with submodules
      - name: Checkout Vita3K repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: true

      # Step 4: Set BOOST_ROOT environment variable
      - name: Set BOOST_ROOT environment variable
        run: echo "BOOST_ROOT=D:/a/Vita3K/Vita3K/external/boost" >> $GITHUB_ENV

      # Step 5: Set CMake Policies to avoid warnings related to Boost
      - name: Set CMake Policies
        run: |
          echo "cmake_policy(SET CMP0144 NEW)" >> CMakeLists.txt
          echo "cmake_policy(SET CMP0167 NEW)" >> CMakeLists.txt

      # Step 6: Run the Visual Studio 2022 Developer Command Prompt
      - name: Run Visual Studio Developer Command Prompt
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

      # Step 7: Generate the Visual Studio project with CMake
      - name: Generate project with CMake
        shell: cmd
        run: cmake --preset windows-vs2022 -Wno-dev

      # Step 8: Build the project
      - name: Build the project
        shell: cmd
        run: cmake --build build/windows-vs2022 --config Release

      # Step 9: Archive the build if needed
      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Vita3K-Build
          path: build/windows-vs2022/bin/Release
